import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styled from "styled-components"

const S = {
	Container: styled.div`
		max-width: 900px;
		width: 100%;
		margin: 0 auto;
		padding: 0 15px;
	`,
	Title: styled.h1`
		color: ${p => p.theme.colors.primary};
	`,
}

const Home: NextPage = () => {
	return (
		<S.Container>
			<Head>
				<title>Starting project</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<S.Title>This is starting project for Next.js</S.Title>
			</main>

			<footer>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer">
					Go to GitHub{" "}
					<span>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</S.Container>
	)
}

export default Home
